#ifndef VARIABLE_LENGTH_QUANTITY_LIBRARY_H
#define VARIABLE_LENGTH_QUANTITY_LIBRARY_H

unsigned long int convertVariableLengthQuantityToUnsignedLongIntAndMoveTheIndexPastTheVariableLengthQuantityValue(unsigned char** thisIsAPointerToAPointerThatShouldPointToTheStartOfTheVariableLengthQuantityValueAndShouldBeMovedOneBytePastTheEndOfTheVariableLengthQuantityValue);

#endif
