#ifndef COMMONFILES_MULTIMEDIACOMPONENTLIBRARY_MULTIMEDIACOMPONENTS_ALLMULTIMEDIACOMPONENTS_H_
#define COMMONFILES_MULTIMEDIACOMPONENTLIBRARY_MULTIMEDIACOMPONENTS_ALLMULTIMEDIACOMPONENTS_H_

#include "MultimediaComponent.h"
#include "MMCImage.h"

#endif /* COMMONFILES_MULTIMEDIACOMPONENTLIBRARY_MULTIMEDIACOMPONENTS_ALLMULTIMEDIACOMPONENTS_H_ */
